### ISSUE TITLE
Resource ordering

### ISSUE THREAD

**Issue by jschaeff** [camptocamp/puppet-dell#36]
The dell::hwtools class needs the configuration of the package repository wich will only be setup afterwards (in dell::openmanage).

The ordering does not seem straightforward to describe because the 2 classes should stay "independent" ...

**Comment by raphink** [comment]
@stumped2 @jschaeff does https://github.com/camptocamp/puppet-dell/pull/50 fix it?

**Comment by stumped2** [comment]
@raphink I just finished getting test-kitchen + puppet set up, I'll test out #50 and let you know.

**Comment by raphink** [comment]
Cool. How does test-kitchen+puppet compare with beaker?

**Comment by stumped2** [comment]
@raphink I originally started out my SysAdmin days using chef, so I am sort of biased towards test-kitchen since it was such a great tool in the chef world.

For the most part, test kitchen + puppet is great, if you don't want to do advanced/weird things since the puppet provisioner docs are sorely lacking.

I did a quick glance at beaker, and it looks cool, but it would take a bit for me to convert over to beaker setup from test kitchen.

**Comment by raphink** [comment]
What are the advantages of test-kitchen?

**Comment by stumped2** [comment]
In what aspect do you mean?
